-- Run this SQL in your Supabase SQL Editor
-- Go to: https://supabase.com/dashboard → Your Project → SQL Editor

-- Create reference tables
CREATE TABLE IF NOT EXISTS "reference_barangay" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "name" varchar(100) NOT NULL, 
    "code" varchar(20) NOT NULL, 
    "description" text NOT NULL, 
    "is_active" boolean NOT NULL, 
    "created_at" timestamp with time zone NOT NULL, 
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "reference_position" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "name" varchar(100) NOT NULL, 
    "code" varchar(20) NOT NULL, 
    "description" text NOT NULL, 
    "is_active" boolean NOT NULL, 
    "created_at" timestamp with time zone NOT NULL, 
    "updated_at" timestamp with time zone NOT NULL
);

-- Create sessions table
CREATE TABLE IF NOT EXISTS "django_session" (
    "session_key" varchar(40) NOT NULL PRIMARY KEY,
    "session_data" text NOT NULL,
    "expire_date" timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");

-- Mark migrations as applied
INSERT INTO django_migrations (app, name, applied) 
VALUES 
    ('reference', '0001_initial', NOW()),
    ('sessions', '0001_initial', NOW())
ON CONFLICT DO NOTHING;
