-- STEP 1: Run this first
CREATE TABLE IF NOT EXISTS "reference_barangay" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "name" varchar(100) NOT NULL, 
    "code" varchar(20) NOT NULL, 
    "description" text NOT NULL, 
    "is_active" boolean NOT NULL, 
    "created_at" timestamp with time zone NOT NULL, 
    "updated_at" timestamp with time zone NOT NULL
);

-- STEP 2: Run this second (after Step 1 succeeds)
CREATE TABLE IF NOT EXISTS "reference_position" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "name" varchar(100) NOT NULL, 
    "code" varchar(20) NOT NULL, 
    "description" text NOT NULL, 
    "is_active" boolean NOT NULL, 
    "created_at" timestamp with time zone NOT NULL, 
    "updated_at" timestamp with time zone NOT NULL
);

-- STEP 3: Run this third
CREATE TABLE IF NOT EXISTS "django_session" (
    "session_key" varchar(40) NOT NULL PRIMARY KEY,
    "session_data" text NOT NULL,
    "expire_date" timestamp with time zone NOT NULL
);

-- STEP 4: Run this fourth
CREATE INDEX IF NOT EXISTS "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");

-- STEP 5: Run this fifth
INSERT INTO django_migrations (app, name, applied) 
VALUES ('reference', '0001_initial', NOW())
ON CONFLICT DO NOTHING;

-- STEP 6: Run this last
INSERT INTO django_migrations (app, name, applied) 
VALUES ('sessions', '0001_initial', NOW())
ON CONFLICT DO NOTHING;
