# Generated by Django 5.2.7 on 2026-02-13 08:18

from django.db import migrations, models


def migrate_description_to_municipality(apps, schema_editor):
    """Copy description field data to municipality field before removing description."""
    Barangay = apps.get_model('reference', 'Barangay')
    for barangay in Barangay.objects.all():
        if barangay.description:
            # Copy description to municipality (truncate if too long)
            barangay.municipality = barangay.description[:100]
            barangay.save()


def reverse_migrate(apps, schema_editor):
    """Reverse migration: copy municipality back to description."""
    Barangay = apps.get_model('reference', 'Barangay')
    for barangay in Barangay.objects.all():
        if barangay.municipality:
            barangay.description = barangay.municipality
            barangay.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        # Add municipality field first
        migrations.AddField(
            model_name='barangay',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        # Migrate data from description to municipality
        migrations.RunPython(migrate_description_to_municipality, reverse_migrate),
        # Remove description field
        migrations.RemoveField(
            model_name='barangay',
            name='description',
        ),
    ]
