# Generated by Django 4.2.12 on 2026-02-16 07:02

from django.db import migrations


def populate_palawan_municipalities(apps, schema_editor):
    """Populate all municipalities in Palawan."""
    Municipality = apps.get_model('reference', 'Municipality')
    
    # All municipalities and city in Palawan
    municipalities = [
        'Aborlan',
        'Agutaya',
        'Araceli',
        'Balabac',
        'Bataraza',
        "Brooke's Point",
        'Busuanga',
        'Cagayancillo',
        'Coron',
        'Culion',
        'Cuyo',
        'Dumaran',
        'El Nido',
        'Kalayaan',
        'Linapacan',
        'Magsaysay',
        'Narra',
        'Puerto Princesa City',
        'Quezon',
        'Rizal',
        'Roxas',
        'San Vicente',
        'Sofronio Española',
        'Taytay',
    ]
    
    # Create municipality records
    for municipality_name in municipalities:
        Municipality.objects.get_or_create(
            name=municipality_name,
            defaults={
                'province': 'Palawan',
                'is_active': True
            }
        )


def reverse_populate(apps, schema_editor):
    """Remove all municipalities if migration is reversed."""
    Municipality = apps.get_model('reference', 'Municipality')
    Municipality.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_municipality_barangay_municipality_old_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_palawan_municipalities, reverse_populate),
    ]
