# Generated by Django 4.2.12 on 2026-02-16 07:03

from django.db import migrations


def migrate_municipality_data(apps, schema_editor):
    """Migrate municipality data from CharField to ForeignKey."""
    Barangay = apps.get_model('reference', 'Barangay')
    Municipality = apps.get_model('reference', 'Municipality')
    
    # Get all barangays
    for barangay in Barangay.objects.all():
        if barangay.municipality_old:
            # Try to find matching municipality
            try:
                municipality = Municipality.objects.get(name__iexact=barangay.municipality_old.strip())
                barangay.municipality = municipality
                barangay.save(update_fields=['municipality'])
            except Municipality.DoesNotExist:
                # If municipality doesn't exist, leave it as None
                print(f"Warning: Municipality '{barangay.municipality_old}' not found for barangay '{barangay.name}'")
            except Municipality.MultipleObjectsReturned:
                # If multiple matches, use the first one
                municipality = Municipality.objects.filter(name__iexact=barangay.municipality_old.strip()).first()
                barangay.municipality = municipality
                barangay.save(update_fields=['municipality'])


def reverse_migrate(apps, schema_editor):
    """Reverse migration - copy ForeignKey data back to CharField."""
    Barangay = apps.get_model('reference', 'Barangay')
    
    for barangay in Barangay.objects.all():
        if barangay.municipality:
            barangay.municipality_old = barangay.municipality.name
            barangay.save(update_fields=['municipality_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20260216_1502'),
    ]

    operations = [
        migrations.RunPython(migrate_municipality_data, reverse_migrate),
    ]
