# Generated by Django 4.2.12 on 2026-02-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_auto_20260216_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='municipality_old',
        ),
    ]
