# Generated by Django 4.2.12 on 2026-02-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_remove_barangay_municipality_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barangays', to='reference.municipality'),
        ),
    ]
