# Generated by Django 5.2.7 on 2026-02-25 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_delete_in_operations', models.BooleanField(default=False, help_text='Allow this user to delete records in Operations (Coordinator, Barangay Officials, Residents, etc.)')),
                ('can_delete_in_reference', models.BooleanField(default=False, help_text='Allow this user to delete records in Reference (Barangay, Positions, etc.)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
    ]
