# Generated by Django 5.2.11 on 2026-03-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_add_user_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_operations',
            field=models.BooleanField(default=False, help_text='Allow managing all Operations sections (Coordinator, Barangay Officials, Residents, Voters).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_operations_barangay_official',
            field=models.BooleanField(default=False, help_text='Allow managing Barangay Officials (add, edit, delete).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_operations_coordinator',
            field=models.BooleanField(default=False, help_text='Allow managing Coordinator records (add, edit, delete).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_operations_residents_record',
            field=models.BooleanField(default=False, help_text='Allow managing Residents Record (add, edit, delete).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_operations_voters_registration',
            field=models.BooleanField(default=False, help_text='Allow managing via Voters Registration screen (edit voter info).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_reference',
            field=models.BooleanField(default=False, help_text='Allow managing all Reference sections (Barangay and Positions).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_reference_barangay',
            field=models.BooleanField(default=False, help_text='Allow managing Barangay under Reference (add, edit, delete).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_reference_position',
            field=models.BooleanField(default=False, help_text='Allow managing Position under Reference (add, edit, delete).'),
        ),
    ]
