# Generated by Django 5.2.11 on 2026-03-09 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_userprofile_can_add_operations_barangay_official_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_plain', models.TextField(blank=True)),
                ('email_type', models.CharField(choices=[('password_change', 'Password Change'), ('other', 'Other')], default='other', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, help_text='User this email was about (e.g. user whose password was changed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sent email',
                'verbose_name_plural': 'Sent emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
