# Generated by Django 5.2.11 on 2026-03-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_add_sent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Password reset code',
                'verbose_name_plural': 'Password reset codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='email_type',
            field=models.CharField(choices=[('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
