# Generated by Django 5.2.11 on 2026-03-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_add_password_change_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordChangeRequest',
        ),
    ]
