# Generated by Django 5.2.11 on 2026-03-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_add_password_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchangerequest',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When admin viewed this request', null=True),
        ),
    ]
