# Generated by Django 4.2.12 on 2026-02-16 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0002_change_description_to_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ALIVE', 'Alive'), ('DECEASED', 'Deceased')], default='ALIVE', max_length=10)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('purok', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=50)),
                ('civil_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], max_length=20)),
                ('educational_attainment', models.CharField(choices=[('ELEMENTARY LEVEL', 'Elementary Level'), ('ELEMENTARY GRADUATE', 'Elementary Graduate'), ('HIGH SCHOOL LEVEL', 'High School Level'), ('HIGH SCHOOL GRADUATE', 'High School Graduate'), ('COLLEGE LEVEL', 'College Level'), ('COLLEGE GRADUATE', 'College Graduate'), ('VOCATIONAL', 'Vocational'), ('POST GRADUATE', 'Post Graduate')], max_length=50)),
                ('citizenship', models.CharField(max_length=100)),
                ('dialect_ethnic', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('PWD', 'PWD'), ('WITH ILLNESS', 'With Illness')], max_length=50)),
                ('economic_status', models.CharField(choices=[('INDIGENT', 'Indigent'), ('LOW INCOME', 'Low Income'), ('MIDDLE INCOME', 'Middle Income'), ('HIGH INCOME', 'High Income'), ('4PS MEMBER', '4PS Member'), ('SENIOR CITIZEN', 'Senior Citizen'), ('SOLO PARENT', 'Solo Parent')], max_length=50)),
                ('is_voter', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='reference.barangay')),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ['-created_at'],
            },
        ),
    ]
