# Generated by Django 4.2.12 on 2026-02-16 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_change_description_to_municipality'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='civil_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOW', 'Widow'), ('SEPARATED', 'Separated'), ('LIVE-IN', 'Live-In')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resident',
            name='economic_status',
            field=models.CharField(choices=[('SOLO PARENT', 'Solo Parent'), ('SENIOR CITIZEN', 'Senior Citizen'), ('NHTS MEMBER', 'NHTS Member'), ('4PS MEMBER', '4PS Member'), ('OUT OF SCHOOL', 'Out of School'), ('IN SCHOOL', 'In School'), ('WITH BUSINESS', 'With Business')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='educational_attainment',
            field=models.CharField(choices=[('DAY CARE STUDENT', 'Day Care Student'), ('ELEMENTARY LEVEL', 'Elementary Level'), ('ELEMENTARY GRADUATE', 'Elementary Graduate'), ('HIGH SCHOOL LEVEL', 'High School Level'), ('HIGH SCHOOL GRADUATE', 'High School Graduate'), ('COLLEGE LEVEL', 'College Level'), ('COLLEGE GRADUATE', 'College Graduate'), ('VOCATIONAL GRADUATE', 'Vocational Graduate'), ('POST GRADUATE', 'Post Graduate'), ('ALTERNATIVE LEARNING SYSTEM', 'Alternative Learning System')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='health_status',
            field=models.CharField(choices=[('PWD', 'PWD'), ('SMOKER', 'Smoker'), ('HYPERTENSION', 'Hypertension'), ('DIABETIC', 'Diabetic'), ('MENTAL HEALTH', 'Mental Health')], max_length=50),
        ),
        migrations.CreateModel(
            name='BarangayOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='reference.barangay')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='reference.position')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_positions', to='operations.resident')),
            ],
            options={
                'verbose_name': 'Barangay Official',
                'verbose_name_plural': 'Barangay Officials',
                'ordering': ['-created_at'],
                'unique_together': {('resident', 'barangay', 'position', 'is_active')},
            },
        ),
    ]
