# Generated by Django 5.2.7 on 2026-02-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_resident_civil_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coordinator Position',
                'verbose_name_plural': 'Coordinator Positions',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['id'], 'verbose_name': 'Resident', 'verbose_name_plural': 'Residents'},
        ),
    ]
