# Generated by Django 5.2.7 on 2026-02-18 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_coordinator_position'),
        ('reference', '0007_alter_barangay_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('contact_no', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinators', to='reference.barangay')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordinators', to='operations.coordinatorposition')),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
                'ordering': ['barangay', 'fullname'],
            },
        ),
    ]
