# Generated by Django 5.2.7 on 2026-02-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_coordinator_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='health_status',
            field=models.CharField(choices=[('PWD', 'PWD'), ('SMOKER', 'Smoker'), ('HYPERTENSION', 'Hypertension'), ('DIABETIC', 'Diabetic'), ('MENTAL HEALTH', 'Mental Health'), ('HEALTHY', 'Healthy')], max_length=50),
        ),
    ]
