# Generated by Django 5.2.7 on 2026-02-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_resident_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='precinct_number',
            field=models.CharField(blank=True, help_text='Precinct number for voter registration', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='voter_legend',
            field=models.CharField(blank=True, choices=[('', '—'), ('A', 'A - Illiterate'), ('B', 'B - PWD'), ('C', 'C - Senior Citizen')], help_text='Voter legend: A=Illiterate, B=PWD, C=Senior Citizen', max_length=10),
        ),
    ]
