# Generated by Django 5.2.7 on 2026-02-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_add_voter_precinct_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='date_verified',
            field=models.DateField(blank=True, help_text='Date the voter record was verified', null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Name or username of person who verified', max_length=150),
        ),
    ]
