# Generated by Django 5.2.7 on 2026-02-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_add_voter_date_verified_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='voter_legend',
            field=models.CharField(blank=True, help_text='Voter legend: comma-separated A=Illiterate, B=PWD, C=Senior (e.g. A,B or A,B,C)', max_length=20),
        ),
    ]
