# Generated by Django 5.2.7 on 2026-02-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_voter_legend_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='residents/'),
        ),
    ]
