# Generated by Django 5.2.7 on 2026-03-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_add_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Profile image URL in Supabase Storage', max_length=500),
        ),
        migrations.AddField(
            model_name='resident',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='QR code image URL in Supabase Storage', max_length=500),
        ),
    ]
