# Generated by Django 5.2.11 on 2026-03-05 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_add_supabase_storage_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangayofficial',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_positions', to='operations.resident'),
        ),
    ]
