# Generated by Django 5.2.11 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_alter_barangayofficial_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Auto-set when status becomes Deceased', null=True),
        ),
    ]

